spring:
  h2:
    console:
      enabled: true
app:
  datasource:
    blog:
      url: jdbc:h2:mem:blog
      username: sa-blog
      password:

    subscribers:
      url: jdbc:h2:mem:subscribers
      username: sa-subscribers
      password: