spring:
  h2:
    console:
      enabled: true
app:
  datasource:
    blog:
      url: jdbc:mysql://localhost:3306/post?allowPublicKeyRetrieval=true
      username: sa-blog
      password: password

    subscribers:
      url: jdbc:postgresql://localhost:5432/subscribers
      username: sa-subscribers
      password: password